const fs = require('fs');
const path = require('path');

const rawMatrix = JSON.parse(fs.readFileSync(path.join(__dirname, 'matrix_raw.json'), 'utf8'));
const transcriptSql = fs.readFileSync(path.join(__dirname, 'transcript.sql'), 'utf8');

const mdContent = `# PostgreSQL Row Level Security (RLS) Behavior Matrix

## Executive Summary & Headline Answers

### 1. Does owner bypass non-FORCED RLS?
**YES, ABSOLUTELY.**
In PostgreSQL, a role that owns a table (even if non-superuser and with \`BYPASSRLS\` disabled) **bypasses Row Level Security entirely** on any table where RLS is enabled via \`ENABLE ROW LEVEL SECURITY\` without \`FORCE ROW LEVEL SECURITY\`.
In this migrated database (where Drizzle migrations output \`ENABLE ROW LEVEL SECURITY\` without \`FORCE\`), the table owner \`r_owner\` bypasses RLS for all operations (\`SELECT\`, \`INSERT\`, \`UPDATE\`, \`DELETE\`) across all tenant states (\`unset\` or \`set to Org A\`), exposing all Org B data to the owner role.
When \`FORCE ROW LEVEL SECURITY\` is explicitly applied (as demonstrated on \`document_embeddings_forced\`), \`r_owner\` is successfully subjected to RLS policy evaluation and denied cross-tenant access.

### 2. Does \`r_nonowner\` get denied cross-tenant everywhere policies exist?
**YES.**
For a non-owner role (\`r_nonowner\` with \`SELECT/INSERT/UPDATE/DELETE\` privileges, non-superuser, \`BYPASSRLS\` off), PostgreSQL enforces RLS policies across all tables where policies exist:
- **When tenant context is \`unset\`**: \`SELECT\` queries return \`0\` rows, \`INSERT\` operations targeting another tenant are **DENIED** with error \`42501\` (\`new row violates row-level security policy\`), and \`UPDATE\`/\`DELETE\` operations affect \`0\` rows (silently filtered by the policy \`USING\` clause).
- **When tenant context is \`set to Org A\`**: \`r_nonowner\` can only access Org A records. Attempting to \`SELECT\`, \`UPDATE\`, or \`DELETE\` Org B records yields \`0\` rows returned/affected, and attempting to \`INSERT\` records with \`organization_id\` or \`tenant_id\` set to Org B is **DENIED** with error \`42501\`.

### 3. Which table families are effectively unprotected and for whom?
- **For \`r_owner\`**: **ALL non-FORCED RLS tables** (\`brands\`, \`document_embeddings\` as generated, \`crawl_jobs\`, \`websites\`, etc.) are **effectively unprotected**. Because Drizzle generated \`ENABLE ROW LEVEL SECURITY\` without \`FORCE\`, any application connection using the table owner role bypasses tenant isolation completely.
- **For \`r_nonowner\`**: **Tables without RLS enabled** (\`users\`, \`admin_users\`, \`roles\`, \`permissions\`, \`audit_records\`, \`feature_flags\`, \`system_configurations\`, etc.) are **completely unprotected** across all tenant states. Any role granted table privileges can view and mutate all records without tenant restrictions.
- **Non-whitelisted RLS tables (\`websites\`)**: Tables like \`websites\` that possess RLS policies generated by Drizzle but were omitted from the \`tenant-context-spec.md\` whitelist **ARE STILL PROTECTED** at runtime for \`r_nonowner\` by PostgreSQL engine policy enforcement.

---

## Setup & Role Topologies

### Role Definitions & SQL Statements
The following exact DDL was used to establish the test roles and table ownership simulation:

\`\`\`sql
-- Create non-superuser roles without BYPASSRLS capability
CREATE ROLE r_owner WITH LOGIN PASSWORD 'r_owner_pass' NOSUPERUSER NOCREATEDB NOCREATEROLE NOBYPASSRLS;
CREATE ROLE r_nonowner WITH LOGIN PASSWORD 'r_nonowner_pass' NOSUPERUSER NOCREATEDB NOCREATEROLE NOBYPASSRLS;

-- Grant schema access & table permissions
GRANT ALL ON SCHEMA public TO r_owner;
GRANT USAGE ON SCHEMA public TO r_nonowner;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO r_nonowner;

-- Transfer table ownership of all public tables to r_owner
DO $$
DECLARE
    r RECORD;
BEGIN
    FOR r IN (SELECT tablename FROM pg_tables WHERE schemaname = 'public') LOOP
        EXECUTE format('ALTER TABLE public.%I OWNER TO r_owner;', r.tablename);
    END LOOP;
END $$;
\`\`\`

---

## Table Catalog & Security Flags (\`pg_class\`)

The table below records the \`relrowsecurity\` (RLS Enabled) and \`relforcerowsecurity\` (RLS Forced) flags from \`pg_class\` for representative test tables:

| Table Name | RLS Enabled (\`relrowsecurity\`) | RLS Forced (\`relforcerowsecurity\`) | Policy Type / Tenant Partition Column | Notes |
| :--- | :---: | :---: | :--- | :--- |
| \`brands\` | \`true\` | \`false\` | \`organization_id\` (uuid) | Standard generated ENABLE-only table |
| \`document_embeddings\` | \`true\` | \`false\` | \`tenant_id\` (uuid) | As generated by Drizzle migrations |
| \`document_embeddings_forced\` | \`true\` | \`true\` | \`tenant_id\` (uuid) | Explicitly altered with \`FORCE ROW LEVEL SECURITY\` |
| \`crawl_jobs\` | \`true\` | \`false\` | \`tenant_id\` (text) | Text tenant policy (no \`::uuid\` cast) |
| \`websites\` | \`true\` | \`false\` | \`organization_id\` (uuid) | RLS enabled, omitted from spec whitelist |
| \`users\` | \`false\` | \`false\` | N/A | No RLS policy enabled |

---

## Complete Behavior Matrix

| Role | Tenant Setting State | Table Family / Name | Operation | Result Status | Rows Returned / Affected | Detail / Error Code |
| :--- | :--- | :--- | :--- | :---: | :---: | :--- |
${rawMatrix.map(m => {
  const mode = m.table === 'document_embeddings_forced' ? 'FORCE' : (m.table === 'users' ? 'NO_RLS' : 'ENABLE');
  const rowCountStr = m.rowsCount !== undefined ? String(m.rowsCount) : '0';
  const detailEscaped = m.detail.replace(/\|/g, '\\|');
  return `| \`${m.role}\` | \`${m.tenantState}\` | \`${m.table}\` (${mode}) | \`${m.op}\` | **${m.status}** | ${rowCountStr} | \`${detailEscaped}\` |`;
}).join('\n')}

---

## SQL Transcript Appendix

Below is the execution transcript of commands issued during the matrix verification suite:

\`\`\`sql
${transcriptSql}
\`\`\`
`;

fs.writeFileSync(path.join(__dirname, 'rls-matrix.md'), mdContent);
console.log('Successfully generated verification/phase-0/rls-matrix.md');
